version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 8089:8089
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  static_volume:
  media_volume:
